title: Testing the jekyll
author: Lachlan Gordon
email: lachlanwgordon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a website all about me and all the things i do and all the things i see.

# social links
twitter_username: lachlanwgordon
github_username:  lachlanwgordon

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
